---

- name: Find my public ip
  uri:
    url: http://ifconfig.me/ip
    return_content: yes
  register: ip_response

- name: ovpn_genconfig
  docker_container:
    name: openvpn-server
    image: kylemanna/openvpn
    state: started
    cleanup: yes
    detach: no
    auto_remove: yes
    command: "ovpn_genconfig -u udp://{{ ip_response.content }} -d -N -p 'route {{ route }}'"
    volumes:
      - "{{ data_vol_name }}:/etc/openvpn"

- name: ovpn_initpki
  docker_container:
    name: openvpn-server
    image: kylemanna/openvpn
    state: started
    cleanup: yes
    detach: no
    auto_remove: yes
    command: "ovpn_initpki nopass"
    volumes:
      - "{{ data_vol_name }}:/etc/openvpn"
    env:
      EASYRSA_BATCH: "yes"

- name: create client
  docker_container:
    name: openvpn-server
    image: kylemanna/openvpn
    state: started
    cleanup: yes
    detach: no
    auto_remove: yes
    command: "easyrsa build-client-full {{ client_name }} nopass"
    volumes:
      - "{{ data_vol_name }}:/etc/openvpn"
    env:
      EASYRSA_BATCH: "yes"

- name: get client config
  docker_container:
    name: openvpn-server-get-conf
    image: kylemanna/openvpn
    state: started
    cleanup: yes
    detach: no
    #auto_remove: yes
    command: "ovpn_getclient {{ client_name }} combined -e "
    volumes:
      - "{{ data_vol_name }}:/etc/openvpn"
  register: config

- name: "Save config to your home"
  local_action:
    copy content="{{ config.ansible_facts.docker_container.Output }}" dest="ovpn_{{ ip_response.content }}.ovpn"

- name: delete container - get client config
  docker_container:
    name: openvpn-server-get-conf
    state: absent
